version: "3.1"

services:
  couchdb:
    image: couchdb
    restart: always
    ports:
      - 5984:5984
    environment:
      INITDB_DATABASE: schoolsdb
    networks:
      - api
  schools:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=couchdb
      - LOG_LEVEL=debug
      - SALT=kikoo plop
    depends_on:
      - couchdb
    networks:
      - api

networks:
  api: